  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define Carnival Core Switch Provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: Carnival Core Switch Config
    ios_config:
      timeout: 60
      #lines: hostname Test1
      provider: "{{ provider }}"
      authorize: yes
      src: "~/Carnival/roles/cc-3850-core/files/cc-3850-core.cfg"
      save_when: modified